# Generated by Django 5.1.4 on 2025-01-14 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='productad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prname', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('price', models.BigIntegerField()),
                ('image', models.FileField(upload_to='file')),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='reg_form',
            name='image',
        ),
    ]
