# Generated by Django 5.1.4 on 2025-01-14 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_productad_remove_reg_form_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productad',
            name='price',
            field=models.CharField(max_length=50),
        ),
    ]
